### ISSUE TITLE
Singleton per request object

### ISSUE THREAD

**Issue by omarkohl** [mmerickel/pyramid_services#11]
One issue I ran into with your **dbsession** service example (that uses a service factory) is the following:

When looking for the service different sessions are returned depending on the context. This is by design. Citing the documentation:

> The factory will be used at most once per request/context/name combination.

Having different DB session in one request is quite ugly and I can think of no use case for it. How did I end up with different contexts? By using the _request_ object outside a view function invoked directly with _pyramid.threadlocal.get_current_request_ . In that case the context is None.

This example by [Jon Rosebaugh - What the Zope Transaction Manager Means To Me (and you)](https://metaclassical.com/what-the-zope-transaction-manager-means-to-me-and-you/) would work but I wanted to use _pyramid_services_ (for consistency, because I'm already using it in other parts of the application).

I'm aware that this might not be the place for this since it classifies more as a question than an issue, but you could at least fix the example to be more clear that

``` python
request.find_service(name='db')
```

will return different sessions depending on the request context.

My workaround is to always pass context=None:

``` python
request.find_service(name='db', context=None)
```

Is there a simpler solution (e.g. a singleton per request)? _register_service()_ would register a singleton object for the whole application, but I do want a different DB session for every request.

**Comment by mmerickel** [comment]
I see what you're saying. Ideally we would use the original `context` interface as the cache key, not the context supplied.

**Comment by mmerickel** [comment]
We can certainly make that change. I'm not sure it's entirely obvious how to go about it right now, but if you want to investigate please feel free to open a PR with a fix or even just add a test case to the test suite.
