### ISSUE TITLE
Using one service in another service?

### ISSUE THREAD

**Issue by piotr-dobrogost** [mmerickel/pyramid_services#16]
Sometimes it might be convenient to use other services when implementing a new service.
Is this a good approach and are there any possible problems associated with it?

**Comment by mmerickel** [comment]
I think that services using other services in a hierarchy is one of the main goals of the library and should be relatively clear from the readme unless I'm misunderstanding something. Every service factory has access to the registry to access other services.

**Comment by piotr-dobrogost** [comment]
One obvious problem with interconnected entities is the risk of creating loops. I understand your solution to this is to have an explicit top-down hierarchy of services and the library does not aim to detect any loops among services?

**Comment by mmerickel** [comment]
That's correct, if you create loops you do so at your own peril. The library doesn't actually track which services are used with which other services, and if you do create a loop between factories you should expect a recursion error.
