### ISSUE TITLE
How to use pyramid_services in tests

### ISSUE THREAD

**Issue by pior** [mmerickel/pyramid_services#5]
For the test setup, I usually config.include() the main application includeme() and then config.include test stuff, to override some of the services/utilities.
It's less intrusive, test code is clearly isolated.

I really like pyramid_services. It's neat and clean. 
However it's not possible to "override" a service (same context, name). 

How do you test the application if some service must be swapped with "test" service ?

**Comment by mmerickel** [comment]
Hey @pior we chatted in #pyramid already (I'm raydeo). I'll add a note here just incase it helps someone else. We discussed two options.

1) Pyramid supports natively overriding most config directives based on its commit-cycle. So you can simply `config.commit()` and then add a new service for that `(iface, context, name)` combo. This requires access to the config object though which only works well in unit tests.

2) You can use an ini setting or something to dispatch your code to register different services at config time.

``` python
if asbool(config.registry.settings.get('use_dummy_services', False)):
    register_dummy_services(config)
else:
    register_default_services(config)
```

This is brute force but clean and you can add extra config settings if you want more fine-grained knobs on which services you are replacing.

**Comment by omarkohl** [comment]
Concerning the _more fine-grained knobs_ that @mmerickel mentioned I suggest the following:

Have several implementations of a service (real, dummy) with the same interface and define which class to use in the .ini file:

```
service.my_service.class = pkg1.pkg2.mod.DummyServiceClass
# service.my_service.class = pkg1.pkg2.mod.RealServiceClass
```

Load the class in your code:

``` python
full_class_path = config.registry.settings.get('service.my_service.class', None)
module_name, class_name = full_class_path.rsplit('.', 1)
module = import_module(module_name)
service_class = getattr(module, class_name)
service_obj = service_class()  # Possibly passing additional parameters
config.register_service(service_obj, IServiceClass)
```

Note that the code has been simplified (e.g. all error handling is missing) but it gives the general idea.
